# Generated by Django 4.0.6 on 2022-08-17 04:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapi', '0004_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('in_cart', 'in_cart'), ('order_placed', 'order_placed'), ('cancelled', 'cancelled')], default='in_cart', max_length=20),
        ),
        migrations.CreateModel(
            name='ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('order_placed', 'order_placed'), ('ready_to_ship', 'ready_to_ship'), ('intransit', 'intranasit'), ('delivered', 'delivered')], default='order_placed', max_length=20)),
                ('expected_delivery', models.DateField(default=datetime.date(2022, 8, 22), null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapi.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
